---
# tasks file for nfs-server
- name: Install nfs-server
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
    - nfs-common
    - nfs-kernel-server
- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs
