---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  pre_tasks:
    - name: check update
      apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
    - name: install netbase
      apt: 
        name: netbase
        state: present
      become: true
  roles:
    - name: "ansible-nfs-server"
      become: true
  # tasks:
  #   - name: "Include ansible-nfs-server"
  #     include_role:
  #       name: "ansible-nfs-server"
